import { NextResponse } from "next/server";
import { promises as fs } from "fs";
import path from "path";

export async function GET() {
  const appUrl =
    process.env.RENDER_EXTERNAL_URL ||
    process.env.SITE_URL ||
    "https://diagbot-dashboard.onrender.com";

  const lines: string[] = [
    "@echo off",
    "setlocal enabledelayedexpansion",
    "chcp 65001 >nul 2>&1",
    "title XENTRY DiagBot Pro v3.0 - Kurulum",
    "color 0A",
    "mode con: cols=72 lines=45",
    "",
    "echo.",
    "echo  =====================================================",
    "echo    XENTRY DiagBot Pro v3.0 - Tam Kurulum",
    "echo    Mercedes-Benz AI Teshis Ajan Sistemi",
    "echo    SD Connect C4 + XENTRY Otomasyon",
    "echo  =====================================================",
    "echo.",
    "REM --- ADMIN CHECK ---",
    "net session >nul 2>&1",
    "if %errorLevel% neq 0 (",
    "    color 0C",
    "    echo  [HATA] Yonetici haklari gerektirir!",
    "    echo  Dosyaya sag tiklayip: Yonetici olarak calistir",
    "    pause",
    "    exit /b 1",
    ")",
    "echo  [OK] Yonetici haklari dogrulandi.",
    "",
    "REM --- STEP 1: PYTHON ---",
    "echo.",
    "echo  [1/8] Python kontrol ediliyor...",
    "python --version >nul 2>&1",
    "if %errorLevel% equ 0 (",
    "    for /f \"tokens=2\" %%v in ('python --version 2^>^&1') do echo         [OK] Python %%v kurulu",
    ") else (",
    "    echo         Python bulunamadi - kuruluyor...",
    "    echo         (Birkaq dakika surebilir)",
    "    curl -s -o \"%TEMP%\\python-installer.exe\" https://www.python.org/ftp/python/3.12.4/python-3.12.4-amd64.exe",
    "    if exist \"%TEMP%\\python-installer.exe\" (",
    '        "%TEMP%\\python-installer.exe" /quiet InstallAllUsers=1 PrependPath=1 Include_pip=1 Include_tcltk=1',
    "        echo         [OK] Python kuruldu",
    "    ) else (",
    "        echo         [HATA] Python indirilemedi",
    "        echo         https://python.org adresinden indirin",
    "    )",
    ")",
    "del /f /q \"%TEMP%\\python-installer.exe\" >nul 2>&1",
    "",
    "REM --- STEP 2: PATH ---",
    "echo  [2/8] Python PATH kontrol...",
    "where python >nul 2>&1",
    "if %errorLevel% neq 0 (",
    '    set "PATH=%PATH%;C:\\Program Files\\Python312;C:\\Program Files\\Python312\\Scripts"',
    "    echo         [OK] PATH guncellendi",
    ") else (",
    "    echo         [OK] Python PATH mevcut",
    ")",
    "",
    "REM --- STEP 3: AGENT FOLDER ---",
    "echo  [3/8] Agent klasoru olusturuluyor...",
    'set "AGENT_DIR=%LOCALAPPDATA%\\Programs\\XENTRY Agent"',
    'if not exist "%AGENT_DIR%" mkdir "%AGENT_DIR%"',
    'mkdir "%AGENT_DIR%\\reports" >nul 2>&1',
    'mkdir "%AGENT_DIR%\\reports\\screenshots" >nul 2>&1',
    'echo         [OK] %AGENT_DIR%',
    "",
    "REM --- STEP 4: PIP PACKAGES ---",
    "echo  [4/8] Python paketleri kuruluyor...",
    'python -m pip install --quiet pyserial pyautogui Pillow pygetwindow colorama requests pyperclip 2>nul',
    "if %errorLevel% equ 0 (",
    "    echo         [OK] Tum paketler kuruldu",
    ") else (",
    "    echo         [UYARI] Bazi paketler kurulamadi",
    "    echo         Agent tekrar deneyecektir",
    ")",
    "",
    "REM --- STEP 5: AGENT FILES ---",
    "echo  [5/8] Agent dosyalari indiriliyor...",
    `powershell -NoProfile -Command "Invoke-WebRequest -Uri '${appUrl}/api/agent/files/obd_scanner.py' -OutFile '%AGENT_DIR%\\obd_scanner.py' -UseBasicParsing -TimeoutSec 30"`,
    `powershell -NoProfile -Command "Invoke-WebRequest -Uri '${appUrl}/api/agent/files/screen_automator.py' -OutFile '%AGENT_DIR%\\screen_automator.py' -UseBasicParsing -TimeoutSec 30"`,
    `powershell -NoProfile -Command "Invoke-WebRequest -Uri '${appUrl}/api/agent/files/reporter.py' -OutFile '%AGENT_DIR%\\reporter.py' -UseBasicParsing -TimeoutSec 30"`,
    `powershell -NoProfile -Command "Invoke-WebRequest -Uri '${appUrl}/api/agent/files/xentry_agent.py' -OutFile '%AGENT_DIR%\\xentry_agent.py' -UseBasicParsing -TimeoutSec 30"`,
    `powershell -NoProfile -Command "Invoke-WebRequest -Uri '${appUrl}/api/agent/files/config.json' -OutFile '%AGENT_DIR%\\config.json' -UseBasicParsing -TimeoutSec 30"`,
    'echo         [OK] Agent dosyalari indirildi',
    "",
    "REM --- STEP 6: AGENT BATCH FILE ---",
    "echo  [6/8] Agent calistirma dosyasi olusturuluyor...",
    'echo @echo off> "%AGENT_DIR%\\DIAGBOT.bat"',
    'echo chcp 65001 ^>nul 2^>^&1>> "%AGENT_DIR%\\DIAGBOT.bat"',
    'echo title XENTRY DiagBot Pro v3.0>> "%AGENT_DIR%\\DIAGBOT.bat"',
    'echo cd /d "%%~dp0">> "%AGENT_DIR%\\DIAGBOT.bat"',
    'echo python xentry_agent.py>> "%AGENT_DIR%\\DIAGBOT.bat"',
    'echo pause>> "%AGENT_DIR%\\DIAGBOT.bat"',
    'echo         [OK] DIAGBOT.bat olusturuldu',
    "",
    "REM --- STEP 7: SHORTCUTS ---",
    "echo  [7/8] Kisa yollar olusturuluyor...",
    `powershell -NoProfile -Command "$ws = New-Object -ComObject WScript.Shell; $sc = $ws.CreateShortcut([Environment]::GetFolderPath('Desktop') + '\\XENTRY Agent.lnk'); $sc.TargetPath = '%AGENT_DIR%\\DIAGBOT.bat'; $sc.WorkingDirectory = '%AGENT_DIR%'; $sc.Description = 'XENTRY DiagBot Pro'; $sc.IconLocation = 'shell32.dll,21'; $sc.Save()"`,
    `powershell -NoProfile -Command "$ws = New-Object -ComObject WScript.Shell; $sc = $ws.CreateShortcut([Environment]::GetFolderPath('Desktop') + '\\XENTRY Web Panel.lnk'); $sc.TargetPath = '${appUrl}'; $sc.Description = 'XENTRY DiagBot Pro - Web Panel'; $sc.IconLocation = 'shell32.dll,14'; $sc.Save()"`,
    `powershell -NoProfile -Command "$sm = [Environment]::GetFolderPath('StartMenu'); if (!(Test-Path $sm)) { New-Item -ItemType Directory -Path $sm -Force | Out-Null }; $ws = New-Object -ComObject WScript.Shell; $sc = $ws.CreateShortcut($sm + '\\XENTRY Agent.lnk'); $sc.TargetPath = '%AGENT_DIR%\\DIAGBOT.bat'; $sc.WorkingDirectory = '%AGENT_DIR%'; $sc.Description = 'XENTRY DiagBot Pro'; $sc.Save()"`,
    'echo         [OK] Kisayollar olusturuldu',
    "",
    "REM --- STEP 8: VERIFY ---",
    "echo  [8/8] Kurulum dogrulaniyor...",
    "echo.",
    'if exist "%USERPROFILE%\\Desktop\\XENTRY Agent.lnk" (',
    "    echo    [+] Masaustu: XENTRY Agent.lnk",
    ") else (",
    "    echo    [-] Masaustu: XENTRY Agent.lnk - BULUNAMADI",
    ")",
    'if exist "%USERPROFILE%\\Desktop\\XENTRY Web Panel.lnk" (',
    "    echo    [+] Masaustu: XENTRY Web Panel.lnk",
    ") else (",
    "    echo    [-] Masaustu: XENTRY Web Panel.lnk - BULUNAMADI",
    ")",
    'if exist "%AGENT_DIR%\\xentry_agent.py" (',
    "    echo    [+] xentry_agent.py",
    ") else (",
    "    echo    [-] xentry_agent.py - BULUNAMADI",
    ")",
    'if exist "%AGENT_DIR%\\DIAGBOT.bat" (',
    "    echo    [+] DIAGBOT.bat",
    ") else (",
    "    echo    [-] DIAGBOT.bat - BULUNAMADI",
    ")",
    'if exist "%AGENT_DIR%\\obd_scanner.py" (',
    "    echo    [+] obd_scanner.py (SD C4)",
    ") else (",
    "    echo    [-] obd_scanner.py - BULUNAMADI",
    ")",
    'if exist "%AGENT_DIR%\\screen_automator.py" (',
    "    echo    [+] screen_automator.py (XENTRY)",
    ") else (",
    "    echo    [-] screen_automator.py - BULUNAMADI",
    ")",
    "echo.",
    "echo  =====================================================",
    "echo    KURULUM BASARIYLA TAMAMLANDI!",
    "echo  =====================================================",
    "echo.",
    "echo  Masaustunuzde 2 kisayol olusturuldu:",
    "echo    1. XENTRY Agent - Arac Tarama (SD C4 + XENTRY)",
    "echo    2. XENTRY Web Panel - Web Rapor Paneli",
    "echo.",
    "echo  Agent calistirmak icin:",
    "echo    - Masaustundeki XENTRY Agent kisayoluna tiklayin",
    "echo    - SD Connect C4 USB'ye baglayin, kontak acik",
    "echo    - Secim 1: SD C4 ile direkt tarama",
    "echo    - Secim 2: XENTRY ekran otomasyonu",
    "echo    - Secim 3: Birlesik tarama",
    "echo.",
    "echo  Simdi Agent baslatilsin mi? (E/H)",
    'choice /c EH /n /m "  Seciminiz [E/H]: "',
    `if %errorLevel% equ 1 start "" "%AGENT_DIR%\\DIAGBOT.bat"`,
    "echo.",
    "timeout /t 3 >nul",
    "exit /b 0",
    "",
  ];

  const batContent = lines.join("\r\n");

  return new NextResponse(batContent, {
    status: 200,
    headers: {
      "Content-Type": "application/octet-stream",
      "Content-Disposition": "attachment; filename=\"KURULUM.bat\"",
      "Content-Length": String(Buffer.byteLength(batContent, "utf-8")),
    },
  });
}
