import { NextResponse } from "next/server";

export async function GET() {
  const appUrl = process.env.RENDER_EXTERNAL_URL || process.env.SITE_URL || "https://diagbot-dashboard.onrender.com";

  const lines: string[] = [
    "@echo off",
    "setlocal enabledelayedexpansion",
    "chcp 65001 >nul 2>&1",
    "title XENTRY DiagBot Pro - Kurulum",
    "color 0A",
    "mode con: cols=70 lines=35",
    "",
    "echo.",
    "echo  ============================================",
    "echo   XENTRY DiagBot Pro Kurulum Sihirbazi v2.2.0",
    "echo  ============================================",
    "echo.",
    "echo  Mercedes-Benz Otonom Teshis Sistemi",
    "echo.",
    "",
    "set APP_URL=" + appUrl,
    "",
    "net session >nul 2>&1",
    "if %errorLevel% neq 0 (",
    "    color 0C",
    "    echo  [HATA] Yonetici haklari gerektirir!",
    "    echo  Sag tiklayip Yonetici olarak calistirin.",
    "    pause",
    "    exit /b 1",
    ")",
    "echo  [OK] Yonetici haklari dogrulandi.",
    "echo.",
    "",
    "echo  [1/4] Kurulum klasoru olusturuluyor...",
    'set "INSTALL_DIR=%ProgramFiles%\\XENTRY DiagBot Pro"',
    'if not exist "!INSTALL_DIR!" (',
    '    mkdir "!INSTALL_DIR!"',
    "    echo  [OK] Klasor olusturuldu",
    ") else (",
    "    echo  [OK] Klasor zaten mevcut",
    ")",
    "echo.",
    "",
    "echo  [2/4] Masaustu kisayolu olusturuluyor...",
    'set "VBS=%TEMP%\\diagbot_shortcut.vbs"',
    "echo Set WshShell = WScript.CreateObject(\"WScript.Shell\") > \"!VBS!\"",
    'echo Set lnk = WshShell.CreateShortcut(WshShell.SpecialFolders("Desktop") & "\\XENTRY DiagBot Pro.lnk") >> "!VBS!"',
    'echo lnk.TargetPath = "%APP_URL%" >> "!VBS!"',
    'echo lnk.Save >> "!VBS!"',
    "cscript //nologo \"!VBS!\" >nul 2>&1",
    "echo  [OK] Masaustu kisayolu olusturuldu",
    "echo.",
    "",
    "echo  [3/4] Baslat menusu girisi olusturuluyor...",
    'set "SM=%ProgramData%\\Microsoft\\Windows\\Start Menu\\Programs\\XENTRY DiagBot Pro"',
    'if not exist "!SM!" mkdir "!SM!"',
    "echo Set WshShell = WScript.CreateObject(\"WScript.Shell\") > \"!VBS!\"",
    'echo Set lnk = WshShell.CreateShortcut("!SM!\\XENTRY DiagBot Pro.lnk") >> "!VBS!"',
    'echo lnk.TargetPath = "%APP_URL%" >> "!VBS!"',
    'echo lnk.Save >> "!VBS!"',
    "cscript //nologo \"!VBS!\" >nul 2>&1",
    "echo  [OK] Baslat menusu girisi olusturuldu",
    "echo.",
    "",
    "echo  [4/4] Temizlik...",
    'del /f /q "!VBS!" >nul 2>&1',
    "echo  [OK] Temizlik tamamlandi",
    "echo.",
    "",
    "echo.",
    "echo  ============================================",
    "echo    KURULUM BASARIYLA TAMAMLANDI!",
    "echo  ============================================",
    "echo.",
    "echo  Masaustu: XENTRY DiagBot Pro.lnk",
    'echo  Baslat Menusu: XENTRY DiagBot Pro',
    "echo.",
    "echo  Simdi acmak ister misiniz? (E/H)",
    "choice /c EH /n /m \"  Seciminiz [E=Ac, H=Kapat]: \"",
    "if %errorlevel% equ 1 start \"\" \"%APP_URL%\"",
    "echo.",
    "timeout /t 5 >nul",
    "exit /b 0",
    "",
  ];

  const batContent = lines.join("\r\n");

  return new NextResponse(batContent, {
    status: 200,
    headers: {
      "Content-Type": "application/octet-stream",
      "Content-Disposition": "attachment; filename=\"KURULUM.bat\"",
      "Content-Length": String(Buffer.byteLength(batContent, "utf-8")),
    },
  });
}
