import { NextResponse } from "next/server";
import { promises as fs } from "fs";
import path from "path";

export async function GET() {
  const appUrl =
    process.env.RENDER_EXTERNAL_URL ||
    process.env.SITE_URL ||
    "https://diagbot-dashboard.onrender.com";

  // VBS scripts as base64 to avoid all escaping issues
  const vbsDesktop = [
    'Set WshShell = WScript.CreateObject("WScript.Shell")',
    'strDesktop = WshShell.SpecialFolders("Desktop")',
    'Set lnk = WshShell.CreateShortcut(strDesktop & "\\XENTRY DiagBot Pro.lnk")',
    `lnk.TargetPath = "${appUrl}"`,
    'lnk.WindowStyle = 1',
    'lnk.IconLocation = "shell32.dll,14" ',
    'lnk.Description = "XENTRY DiagBot Pro"',
    'lnk.Save',
  ].join("\r\n");

  const vbsAgentDesktop = [
    'Set WshShell = WScript.CreateObject("WScript.Shell")',
    'strDesktop = WshShell.SpecialFolders("Desktop")',
    'Set lnk = WshShell.CreateShortcut(strDesktop & "\\XENTRY Agent.lnk")',
    "lnk.TargetPath = WshShell.ExpandEnvironmentStrings(\"%LOCALAPPDATA%\\Programs\\XENTRY Agent\\xentry_agent.exe\")",
    'lnk.WindowStyle = 1',
    'lnk.IconLocation = "shell32.dll,21" ',
    'lnk.Description = "XENTRY DiagBot Pro - Arac Tarama Agenti"',
    'lnk.Save',
  ].join("\r\n");

  const vbsStartMenu = [
    'Set WshShell = WScript.CreateObject("WScript.Shell")',
    'strSM = WshShell.SpecialFolders("AllUsersStartMenu") & "\\XENTRY DiagBot Pro"',
    'Set fso = CreateObject("Scripting.FileSystemObject")',
    'If Not fso.FolderExists(strSM) Then fso.CreateFolder strSM',
    'Set lnk = WshShell.CreateShortcut(strSM & "\\XENTRY Web Panel.lnk")',
    `lnk.TargetPath = "${appUrl}"`,
    'lnk.WindowStyle = 1',
    'lnk.IconLocation = "shell32.dll,14" ',
    'lnk.Description = "XENTRY DiagBot Pro - Web Panel"',
    'lnk.Save',
    'Set lnk2 = WshShell.CreateShortcut(strSM & "\\XENTRY Agent.lnk")',
    "lnk2.TargetPath = WshShell.ExpandEnvironmentStrings(\"%LOCALAPPDATA%\\Programs\\XENTRY Agent\\xentry_agent.exe\")",
    'lnk2.WindowStyle = 1',
    'lnk2.IconLocation = "shell32.dll,21" ',
    'lnk2.Description = "XENTRY DiagBot Pro - Arac Tarama Agenti"',
    'lnk2.Save',
  ].join("\r\n");

  const b64Desktop = Buffer.from(vbsDesktop, "utf-8").toString("base64");
  const b64AgentDesktop = Buffer.from(vbsAgentDesktop, "utf-8").toString("base64");
  const b64StartMenu = Buffer.from(vbsStartMenu, "utf-8").toString("base64");

  const lines: string[] = [
    "@echo off",
    "setlocal enabledelayedexpansion",
    "chcp 65001 >nul 2>&1",
    "title XENTRY DiagBot Pro - Kurulum Sihirbazi",
    "color 0A",
    "mode con: cols=72 lines=40",
    "",
    "echo.",
    "echo  =====================================================",
    "echo    XENTRY DiagBot Pro v2.2.0 - Tam Kurulum",
    "echo    Mercedes-Benz AI Teshis Ajan Sistemi",
    "echo  =====================================================",
    "echo.",
    "",
    "--- ADMiN KONTROLU ---",
    "net session >nul 2>&1",
    "if %errorLevel% neq 0 (",
    "    color 0C",
    "    echo  [HATA] Bu kurulum yonetici haklari gerektirir!",
    "    echo.",
    "    echo  Dosyaya sag tiklayip:",
    "    echo  Yonetici olarak calistir secin.",
    "    echo.",
    "    pause",
    "    exit /b 1",
    ")",
    "echo  [OK] Yonetici haklari dogrulandi.",
    "",
    "--- ADIM 1: PYTHON KURULUMU ---",
    "echo.",
    "echo  [1/7] Python kontrol ediliyor...",
    "python --version >nul 2>&1",
    "if %errorLevel% equ 0 (",
    "    echo         [OK] Python zaten kurulu",
    ") else (",
    "    echo         Python bulunamadi - kuruluyor...",
    "    echo         (Bu islem birkaç dakika surebilir)",
    "    curl -s -o \"%TEMP%\\python-installer.exe\" https://www.python.org/ftp/python/3.12.4/python-3.12.4-amd64.exe",
    "    if exist \"%TEMP%\\python-installer.exe\" (",
    "        \"%TEMP%\\python-installer.exe\" /quiet InstallAllUsers=1 PrependPath=1 Include_pip=1",
    "        echo         [OK] Python kuruldu",
    "    ) else (",
    "        echo         [HATA] Python indirilemedi",
    "        echo         Lutfen https://python.org adresinden indirin",
    "    )",
    ")",
    "del /f /q \"%TEMP%\\python-installer.exe\" >nul 2>&1",
    "",
    "--- ADIM 2: PATH KONTROLU ---",
    "echo  [2/7] Python PATH kontrol ediliyor...",
    "where python >nul 2>&1",
    "if %errorLevel% neq 0 (",
    "    set \"PATH=%PATH%;C:\\Program Files\\Python312;C:\\Program Files\\Python312\\Scripts\"",
    "    echo         [OK] PATH guncellendi",
    ") else (",
    "    echo         [OK] Python PATH mevcut",
    ")",
    "",
    "--- ADIM 3: AGENT KLASORU ---",
    "echo  [3/7] Agent klasoru olusturuluyor...",
    "set \"AGENT_DIR=%LOCALAPPDATA%\\Programs\\XENTRY Agent\"",
    "if not exist \"%AGENT_DIR%\" mkdir \"%AGENT_DIR%\"",
    "echo         [OK] Klasor: %AGENT_DIR%",
    "",
    "--- ADIM 4: PIP PAKETLERI ---",
    "echo  [4/7] Python paketleri kuruluyor...",
    "echo         (pyserial, pyautogui, Pillow, colorama, requests)",
    "python -m pip install --quiet pyserial pyautogui Pillow pygetwindow colorama requests 2>nul",
    "if %errorLevel% equ 0 (",
    "    echo         [OK] Tum paketler kuruldu",
    ") else (",
    "    echo         [UYARI] Bazi paketler kurulamadi",
    "    echo         Agent calisirsa sorun yoktur",
    ")",
    "",
    "--- ADIM 5: AGENT DOSYALARI ---",
    "echo  [5/7] Agent dosyalari indiriliyor...",
    `powershell -NoProfile -Command "Invoke-WebRequest -Uri '${appUrl}/api/agent/files/obd_scanner.py' -OutFile '%AGENT_DIR%\\obd_scanner.py' -UseBasicParsing -TimeoutSec 30"`,
    `powershell -NoProfile -Command "Invoke-WebRequest -Uri '${appUrl}/api/agent/files/screen_automator.py' -OutFile '%AGENT_DIR%\\screen_automator.py' -UseBasicParsing -TimeoutSec 30"`,
    `powershell -NoProfile -Command "Invoke-WebRequest -Uri '${appUrl}/api/agent/files/reporter.py' -OutFile '%AGENT_DIR%\\reporter.py' -UseBasicParsing -TimeoutSec 30"`,
    `powershell -NoProfile -Command "Invoke-WebRequest -Uri '${appUrl}/api/agent/files/xentry_agent.py' -OutFile '%AGENT_DIR%\\xentry_agent.py' -UseBasicParsing -TimeoutSec 30"`,
    `powershell -NoProfile -Command "Invoke-WebRequest -Uri '${appUrl}/api/agent/files/config.json' -OutFile '%AGENT_DIR%\\config.json' -UseBasicParsing -TimeoutSec 30"`,
    "mkdir \"%AGENT_DIR%\\reports\" >nul 2>&1",
    "echo         [OK] Agent dosyalari indirildi",
    "",
    "--- ADIM 6: KISAYOLLAR ---",
    "echo  [6/7] Kisa yollar olusturuluyor...",
    // Web Panel desktop shortcut
    `powershell -NoProfile -Command "[Text.Encoding]::ASCII.GetString([Convert]::FromBase64String('${b64Desktop}')) | Out-File '%TEMP%\\sc1.vbs' -Encoding ASCII"`,
    "cscript //nologo \"%TEMP%\\sc1.vbs\" >nul 2>&1",
    // Agent desktop shortcut
    `powershell -NoProfile -Command "[Text.Encoding]::ASCII.GetString([Convert]::FromBase64String('${b64AgentDesktop}')) | Out-File '%TEMP%\\sc2.vbs' -Encoding ASCII"`,
    "cscript //nologo \"%TEMP%\\sc2.vbs\" >nul 2>&1",
    // Start Menu shortcuts
    `powershell -NoProfile -Command "[Text.Encoding]::ASCII.GetString([Convert]::FromBase64String('${b64StartMenu}')) | Out-File '%TEMP%\\sc3.vbs' -Encoding ASCII"`,
    "cscript //nologo \"%TEMP%\\sc3.vbs\" >nul 2>&1",
    "del /f /q \"%TEMP%\\sc1.vbs\" >nul 2>&1",
    "del /f /q \"%TEMP%\\sc2.vbs\" >nul 2>&1",
    "del /f /q \"%TEMP%\\sc3.vbs\" >nul 2>&1",
    "echo         [OK] Kisayollar olusturuldu",
    "",
    "--- ADIM 7: DOGRULAMA ---",
    "echo  [7/7] Kurulum dogrulaniyor...",
    "echo.",
    "echo  Masaustu Kisayollar:",
    "if exist \"%USERPROFILE%\\Desktop\\XENTRY DiagBot Pro.lnk\" (",
    "    echo    [+] XENTRY DiagBot Pro.lnk - Web Panel",
    ") else (",
    "    echo    [-] XENTRY DiagBot Pro.lnk - BULUNAMADI",
    ")",
    "if exist \"%USERPROFILE%\\Desktop\\XENTRY Agent.lnk\" (",
    "    echo    [+] XENTRY Agent.lnk - Tarama Agenti",
    ") else (",
    "    echo    [-] XENTRY Agent.lnk - BULUNAMADI",
    ")",
    "echo.",
    "echo  Agent Dosyalari:",
    "if exist \"%AGENT_DIR%\\xentry_agent.py\" (",
    "    echo    [+] xentry_agent.py",
    ") else (",
    "    echo    [-] xentry_agent.py - BULUNAMADI",
    ")",
    "if exist \"%AGENT_DIR%\\obd_scanner.py\" (",
    "    echo    [+] obd_scanner.py",
    ") else (",
    "    echo    [-] obd_scanner.py - BULUNAMADI",
    ")",
    "if exist \"%AGENT_DIR%\\reporter.py\" (",
    "    echo    [+] reporter.py",
    ") else (",
    "    echo    [-] reporter.py - BULUNAMADI",
    ")",
    "echo.",
    "echo  =====================================================",
    "echo    KURULUM BASARIYLA TAMAMLANDI!",
    "echo  =====================================================",
    "echo.",
    "echo  Masaustunuzde 2 kisayol olusturuldu:",
    "echo    1. XENTRY DiagBot Pro - Web Panel (tarayici)",
    "echo    2. XENTRY Agent - Arac Tarama (masaustu)",
    "echo.",
    "echo  Simdi uygulamayi acmak ister misiniz? (E/H)",
    'choice /c EH /n /m "  Seciminiz [E=Ac, H=Kapat]: "',
    `if %errorLevel% equ 1 start "" "${appUrl}"`,
    "echo.",
    "timeout /t 3 >nul",
    "exit /b 0",
    "",
  ];

  const batContent = lines.join("\r\n");

  return new NextResponse(batContent, {
    status: 200,
    headers: {
      "Content-Type": "application/octet-stream",
      "Content-Disposition": "attachment; filename=\"KURULUM.bat\"",
      "Content-Length": String(Buffer.byteLength(batContent, "utf-8")),
    },
  });
}
