import { NextRequest, NextResponse } from 'next/server'
import { db } from '@/lib/db'

// Mercedes-Benz specific fault codes database
const MB_FAULT_CODES: Record<string, { description: string; severity: string; system: string }> = {
  // P-Series (Powertrain)
  'P0010': { description: 'Intake Camshaft Position Actuator Circuit (Bank 1)', severity: 'warning', system: 'Motor Kontrol' },
  'P0011': { description: 'Intake Camshaft Position Timing Over-Advanced (Bank 1)', severity: 'warning', system: 'Motor Kontrol' },
  'P0012': { description: 'Intake Camshaft Position Timing Over-Retarded (Bank 1)', severity: 'warning', system: 'Motor Kontrol' },
  'P0015': { description: 'Intake Camshaft Position Actuator Circuit (Bank 1/B)', severity: 'warning', system: 'Motor Kontrol' },
  'P0016': { description: 'Crankshaft Position - Camshaft Position Correlation (Bank 1 Sensor A)', severity: 'critical', system: 'Motor Kontrol' },
  'P0017': { description: 'Crankshaft Position - Camshaft Position Correlation (Bank 1 Sensor B)', severity: 'critical', system: 'Motor Kontrol' },
  'P0020': { description: 'Intake Camshaft Position Actuator Circuit (Bank 2)', severity: 'warning', system: 'Motor Kontrol' },
  'P0025': { description: 'Intake Camshaft Position Actuator Circuit (Bank 2/B)', severity: 'warning', system: 'Motor Kontrol' },
  'P0030': { description: 'Heated Oxygen Sensor (HO2S) Heater Control Circuit (Bank 1 Sensor 1)', severity: 'warning', system: 'Emisyon' },
  'P0031': { description: 'HO2S Heater Control Circuit Low (Bank 1 Sensor 1)', severity: 'warning', system: 'Emisyon' },
  'P0036': { description: 'HO2S Heater Control Circuit (Bank 1 Sensor 2)', severity: 'warning', system: 'Emisyon' },
  'P0045': { description: 'Turbocharger/Supercharger Boost Control Solenoid A Circuit Open', severity: 'critical', system: 'Turbo' },
  'P0046': { description: 'Turbocharger/Supercharger Boost Control Solenoid A Circuit Range/Performance', severity: 'critical', system: 'Turbo' },
  'P0100': { description: 'Mass Air Flow (MAF) Sensor Circuit', severity: 'warning', system: 'Motor Kontrol' },
  'P0101': { description: 'MAF Sensor Circuit Range/Performance', severity: 'warning', system: 'Motor Kontrol' },
  'P0102': { description: 'MAF Sensor Circuit Low Input', severity: 'warning', system: 'Motor Kontrol' },
  'P0105': { description: 'Manifold Absolute Pressure (MAP) Sensor Circuit', severity: 'warning', system: 'Motor Kontrol' },
  'P0106': { description: 'MAP Sensor Circuit Range/Performance', severity: 'warning', system: 'Motor Kontrol' },
  'P0107': { description: 'MAP Sensor Circuit Low Input', severity: 'warning', system: 'Motor Kontrol' },
  'P0108': { description: 'MAP Sensor Circuit High Input', severity: 'warning', system: 'Motor Kontrol' },
  'P0110': { description: 'Intake Air Temperature (IAT) Sensor Circuit', severity: 'warning', system: 'Motor Kontrol' },
  'P0115': { description: 'Engine Coolant Temperature (ECT) Sensor Circuit', severity: 'warning', system: 'Motor Kontrol' },
  'P0116': { description: 'ECT Sensor Circuit Range/Performance', severity: 'warning', system: 'Motor Kontrol' },
  'P0120': { description: 'Throttle Position Sensor/Pedal Position Sensor A Circuit', severity: 'warning', system: 'Gaz Kelebeği' },
  'P0121': { description: 'TPS/Pedal Position Sensor A Circuit Range/Performance', severity: 'warning', system: 'Gaz Kelebeği' },
  'P0125': { description: 'Insufficient Coolant Temperature for Closed Loop Fuel Control', severity: 'warning', system: 'Soğutma' },
  'P0130': { description: 'O2 Sensor Circuit (Bank 1 Sensor 1)', severity: 'warning', system: 'Emisyon' },
  'P0131': { description: 'O2 Sensor Circuit Low Voltage (Bank 1 Sensor 1)', severity: 'warning', system: 'Emisyon' },
  'P0133': { description: 'O2 Sensor Circuit Slow Response (Bank 1 Sensor 1)', severity: 'warning', system: 'Emisyon' },
  'P0134': { description: 'O2 Sensor Circuit No Activity Detected (Bank 1 Sensor 1)', severity: 'warning', system: 'Emisyon' },
  'P0135': { description: 'O2 Sensor Heater Circuit (Bank 1 Sensor 1)', severity: 'warning', system: 'Emisyon' },
  'P0136': { description: 'O2 Sensor Circuit (Bank 1 Sensor 2)', severity: 'warning', system: 'Emisyon' },
  'P0140': { description: 'O2 Sensor Circuit No Activity Detected (Bank 1 Sensor 3)', severity: 'info', system: 'Emisyon' },
  'P0141': { description: 'O2 Sensor Heater Circuit (Bank 1 Sensor 3)', severity: 'warning', system: 'Emisyon' },
  'P0150': { description: 'O2 Sensor Circuit (Bank 2 Sensor 1)', severity: 'warning', system: 'Emisyon' },
  'P0155': { description: 'O2 Sensor Heater Circuit (Bank 2 Sensor 1)', severity: 'warning', system: 'Emisyon' },
  'P0170': { description: 'Fuel Trim Malfunction (Bank 1)', severity: 'warning', system: 'Yakıt Sistemi' },
  'P0171': { description: 'System Too Lean (Bank 1)', severity: 'warning', system: 'Yakıt Sistemi' },
  'P0172': { description: 'System Too Rich (Bank 1)', severity: 'warning', system: 'Yakıt Sistemi' },
  'P0173': { description: 'Fuel Trim Malfunction (Bank 2)', severity: 'warning', system: 'Yakıt Sistemi' },
  'P0174': { description: 'System Too Lean (Bank 2)', severity: 'warning', system: 'Yakıt Sistemi' },
  'P0175': { description: 'System Too Rich (Bank 2)', severity: 'warning', system: 'Yakıt Sistemi' },
  'P0200': { description: 'Injector Circuit Malfunction', severity: 'critical', system: 'Yakıt Sistemi' },
  'P0201': { description: 'Injector Circuit/Open - Cylinder 1', severity: 'critical', system: 'Yakıt Sistemi' },
  'P0202': { description: 'Injector Circuit/Open - Cylinder 2', severity: 'critical', system: 'Yakıt Sistemi' },
  'P0203': { description: 'Injector Circuit/Open - Cylinder 3', severity: 'critical', system: 'Yakıt Sistemi' },
  'P0204': { description: 'Injector Circuit/Open - Cylinder 4', severity: 'critical', system: 'Yakıt Sistemi' },
  'P0205': { description: 'Injector Circuit/Open - Cylinder 5', severity: 'critical', system: 'Yakıt Sistemi' },
  'P0206': { description: 'Injector Circuit/Open - Cylinder 6', severity: 'critical', system: 'Yakıt Sistemi' },
  'P0207': { description: 'Injector Circuit/Open - Cylinder 7', severity: 'critical', system: 'Yakıt Sistemi' },
  'P0208': { description: 'Injector Circuit/Open - Cylinder 8', severity: 'critical', system: 'Yakıt Sistemi' },
  'P0217': { description: 'Engine Overtemperature Condition', severity: 'critical', system: 'Soğutma' },
  'P0219': { description: 'Engine Overspeed Condition', severity: 'critical', system: 'Motor Kontrol' },
  'P0234': { description: 'Turbocharger/Supercharger Boost System Overboost', severity: 'critical', system: 'Turbo' },
  'P0235': { description: 'Turbocharger Boost Sensor A Circuit', severity: 'critical', system: 'Turbo' },
  'P0236': { description: 'Turbocharger Boost Sensor A Circuit Range/Performance', severity: 'warning', system: 'Turbo' },
  'P0245': { description: 'Turbocharger Wastegate Solenoid A Circuit Low', severity: 'critical', system: 'Turbo' },
  'P0261': { description: 'Cylinder 1 Injector Circuit Low', severity: 'critical', system: 'Yakıt Sistemi' },
  'P0264': { description: 'Cylinder 2 Injector Circuit Low', severity: 'critical', system: 'Yakıt Sistemi' },
  'P0299': { description: 'Turbocharger/Supercharger Boost System Underboost', severity: 'warning', system: 'Turbo' },
  'P0300': { description: 'Random/Multiple Cylinder Misfire Detected', severity: 'critical', system: 'Ateşleme' },
  'P0301': { description: 'Cylinder 1 Misfire Detected', severity: 'critical', system: 'Ateşleme' },
  'P0302': { description: 'Cylinder 2 Misfire Detected', severity: 'critical', system: 'Ateşleme' },
  'P0303': { description: 'Cylinder 3 Misfire Detected', severity: 'critical', system: 'Ateşleme' },
  'P0304': { description: 'Cylinder 4 Misfire Detected', severity: 'critical', system: 'Ateşleme' },
  'P0305': { description: 'Cylinder 5 Misfire Detected', severity: 'critical', system: 'Ateşleme' },
  'P0306': { description: 'Cylinder 6 Misfire Detected', severity: 'critical', system: 'Ateşleme' },
  'P0307': { description: 'Cylinder 7 Misfire Detected', severity: 'critical', system: 'Ateşleme' },
  'P0308': { description: 'Cylinder 8 Misfire Detected', severity: 'critical', system: 'Ateşleme' },
  'P0335': { description: 'Crankshaft Position Sensor A Circuit', severity: 'critical', system: 'Motor Kontrol' },
  'P0336': { description: 'Crankshaft Position Sensor A Circuit Range/Performance', severity: 'critical', system: 'Motor Kontrol' },
  'P0340': { description: 'Camshaft Position Sensor A Circuit (Bank 1 or Single Sensor)', severity: 'critical', system: 'Motor Kontrol' },
  'P0341': { description: 'Camshaft Position Sensor A Circuit Range/Performance', severity: 'critical', system: 'Motor Kontrol' },
  'P0343': { description: 'Camshaft Position Sensor A Circuit High Input (Bank 1)', severity: 'critical', system: 'Motor Kontrol' },
  'P0350': { description: 'Ignition Coil Primary/Secondary Circuit', severity: 'critical', system: 'Ateşleme' },
  'P0351': { description: 'Ignition Coil A Primary/Secondary Circuit', severity: 'critical', system: 'Ateşleme' },
  'P0352': { description: 'Ignition Coil B Primary/Secondary Circuit', severity: 'critical', system: 'Ateşleme' },
  'P0353': { description: 'Ignition Coil C Primary/Secondary Circuit', severity: 'critical', system: 'Ateşleme' },
  'P0354': { description: 'Ignition Coil D Primary/Secondary Circuit', severity: 'critical', system: 'Ateşleme' },
  'P0355': { description: 'Ignition Coil E Primary/Secondary Circuit', severity: 'critical', system: 'Ateşleme' },
  'P0356': { description: 'Ignition Coil F Primary/Secondary Circuit', severity: 'critical', system: 'Ateşleme' },
  'P0400': { description: 'Exhaust Gas Recirculation (EGR) Flow', severity: 'warning', system: 'Emisyon' },
  'P0401': { description: 'EGR Flow Insufficient Detected', severity: 'warning', system: 'Emisyon' },
  'P0402': { description: 'EGR Flow Excessive Detected', severity: 'warning', system: 'Emisyon' },
  'P0403': { description: 'EGR Circuit Malfunction', severity: 'warning', system: 'Emisyon' },
  'P0405': { description: 'EGR Sensor A Circuit Low', severity: 'warning', system: 'Emisyon' },
  'P0410': { description: 'Secondary Air Injection System', severity: 'warning', system: 'Emisyon' },
  'P0420': { description: 'Catalyst System Efficiency Below Threshold (Bank 1)', severity: 'warning', system: 'Emisyon' },
  'P0430': { description: 'Catalyst System Efficiency Below Threshold (Bank 2)', severity: 'warning', system: 'Emisyon' },
  'P0441': { description: 'EVAP Control System Incorrect Purge Flow', severity: 'info', system: 'Yakıt Sistemi' },
  'P0442': { description: 'EVAP Control System Leak Detected (Small Leak)', severity: 'info', system: 'Yakıt Sistemi' },
  'P0445': { description: 'EVAP Control System Purge Control Valve Circuit Shorted', severity: 'warning', system: 'Yakıt Sistemi' },
  'P0446': { description: 'EVAP Control System Vent Control Circuit', severity: 'warning', system: 'Yakıt Sistemi' },
  'P0455': { description: 'EVAP Control System Leak Detected (Gross Leak)', severity: 'info', system: 'Yakıt Sistemi' },
  'P0480': { description: 'Cooling Fan Control Circuit', severity: 'warning', system: 'Soğutma' },
  'P0489': { description: 'EGR A Control Circuit Low', severity: 'warning', system: 'Emisyon' },
  'P0490': { description: 'EGR B Control Circuit High', severity: 'warning', system: 'Emisyon' },
  'P0500': { description: 'Vehicle Speed Sensor Malfunction', severity: 'warning', system: 'Şanzıman' },
  'P0505': { description: 'Idle Control System', severity: 'warning', system: 'Motor Kontrol' },
  'P0507': { description: 'Idle Control System RPM Higher Than Expected', severity: 'warning', system: 'Motor Kontrol' },
  'P0544': { description: 'Exhaust Gas Temperature Sensor Circuit (Bank 1 Sensor 1)', severity: 'warning', system: 'Emisyon' },
  'P0545': { description: 'Exhaust Gas Temperature Sensor Circuit Low (Bank 1 Sensor 1)', severity: 'warning', system: 'Emisyon' },
  'P0560': { description: 'System Voltage Unstable', severity: 'critical', system: 'Elektrik' },
  'P0562': { description: 'System Voltage Low', severity: 'critical', system: 'Elektrik' },
  'P0563': { description: 'System Voltage High', severity: 'critical', system: 'Elektrik' },
  'P0600': { description: 'Serial Communication Link Malfunction', severity: 'critical', system: 'Ağ' },
  'P0601': { description: 'Internal Control Module Memory Check Sum Error', severity: 'critical', system: 'ECU' },
  'P0603': { description: 'Internal Control Module Keep Alive Memory (KAM) Error', severity: 'critical', system: 'ECU' },
  'P0606': { description: 'ECM/PCM Processor', severity: 'critical', system: 'ECU' },
  'P0607': { description: 'Control Module Performance', severity: 'critical', system: 'ECU' },
  'P0620': { description: 'Generator Control Circuit', severity: 'warning', system: 'Elektrik' },
  'P0622': { description: 'Generator Field/F Control Circuit', severity: 'warning', system: 'Elektrik' },
  'P062F': { description: 'Internal Control Module EEPROM Error', severity: 'critical', system: 'ECU' },
  'P0700': { description: 'Transmission Control System Malfunction', severity: 'critical', system: 'Şanzıman' },
  'P0705': { description: 'Transmission Range Sensor Circuit Malfunction', severity: 'warning', system: 'Şanzıman' },
  'P0706': { description: 'Transmission Range Sensor Circuit Range/Performance', severity: 'warning', system: 'Şanzıman' },
  'P0710': { description: 'Transmission Fluid Temperature Sensor Circuit', severity: 'warning', system: 'Şanzıman' },
  'P0715': { description: 'Input/Turbine Speed Sensor Circuit', severity: 'warning', system: 'Şanzıman' },
  'P0717': { description: 'Input/Turbine Speed Sensor Circuit No Signal', severity: 'critical', system: 'Şanzıman' },
  'P0720': { description: 'Output Speed Sensor Circuit', severity: 'warning', system: 'Şanzıman' },
  'P0725': { description: 'Engine Speed Input Circuit', severity: 'warning', system: 'Şanzıman' },
  'P0730': { description: 'Incorrect Gear Ratio', severity: 'critical', system: 'Şanzıman' },
  'P0740': { description: 'Torque Converter Clutch Circuit Malfunction', severity: 'warning', system: 'Şanzıman' },
  'P0745': { description: 'Pressure Control Solenoid A', severity: 'warning', system: 'Şanzıman' },
  'P0750': { description: 'Shift Solenoid A Malfunction', severity: 'warning', system: 'Şanzıman' },
  'P0755': { description: 'Shift Solenoid B Malfunction', severity: 'warning', system: 'Şanzıman' },
  'P0765': { description: 'Shift Solenoid C Malfunction', severity: 'warning', system: 'Şanzıman' },
  'P0770': { description: 'Shift Solenoid D Malfunction', severity: 'warning', system: 'Şanzıman' },
  'P0775': { description: 'Pressure Control Solenoid B', severity: 'warning', system: 'Şanzıman' },
  'P0780': { description: 'Shift Malfunction', severity: 'critical', system: 'Şanzıman' },
  'P0900': { description: 'Clutch Actuator Circuit', severity: 'critical', system: 'Şanzıman' },

  // B-Series (Body)
  'B1000': { description: 'Radio Antenna Open/Short Circuit', severity: 'info', system: 'Gövde Elektrik' },
  'B1001': { description: 'Front SAM - Defective or Not Coded', severity: 'warning', system: 'SAM Modülü' },
  'B1002': { description: 'Rear SAM - Defective or Not Coded', severity: 'warning', system: 'SAM Modülü' },
  'B1003': { description: 'Door Control Unit - Defective or Not Coded', severity: 'warning', system: 'Kapı Kontrol' },
  'B1004': { description: 'Interior Sensor Not Coded', severity: 'info', system: 'Güvenlik' },
  'B1005': { description: 'Rear SAM - Power Supply (Terminal 30)', severity: 'warning', system: 'SAM Modülü' },
  'B1006': { description: 'Rear SAM - Power Supply (Terminal 15)', severity: 'warning', system: 'SAM Modülü' },
  'B1010': { description: 'Battery Voltage Supply Terminal 30 Low', severity: 'critical', system: 'Elektrik' },
  'B1011': { description: 'Battery Voltage Supply Terminal 15R Low', severity: 'warning', system: 'Elektrik' },
  'B1012': { description: 'Supply Voltage Terminal 58D Open', severity: 'info', system: 'Elektrik' },
  'B1013': { description: 'Signal L3 CAN-Bus Off', severity: 'critical', system: 'Ağ' },
  'B1014': { description: 'Signal L3 CAN-Bus Faulty', severity: 'critical', system: 'Ağ' },
  'B1015': { description: 'Keyless Go Drive Authorization Not Present', severity: 'warning', system: 'Güvenlik' },
  'B1016': { description: 'Keyless Go System Error', severity: 'warning', system: 'Güvenlik' },
  'B1017': { description: 'Keyless Go ECU (N69/5) - Defective', severity: 'critical', system: 'Güvenlik' },
  'B1020': { description: 'Left Headlamp - Vertical Aim Control', severity: 'info', system: 'Aydınlatma' },
  'B1021': { description: 'Right Headlamp - Vertical Aim Control', severity: 'info', system: 'Aydınlatma' },
  'B1022': { description: 'Left Front Turn Signal Lamp (M2/1)', severity: 'info', system: 'Aydınlatma' },
  'B1023': { description: 'Right Front Turn Signal Lamp (M2/2)', severity: 'info', system: 'Aydınlatma' },
  'B1024': { description: 'Left Front Fog Lamp (E3e1)', severity: 'info', system: 'Aydınlatma' },
  'B1025': { description: 'Right Front Fog Lamp (E3e2)', severity: 'info', system: 'Aydınlatma' },
  'B1026': { description: 'Left Low Beam Lamp (E1e1)', severity: 'info', system: 'Aydınlatma' },
  'B1027': { description: 'Right Low Beam Lamp (E1e2)', severity: 'info', system: 'Aydınlatma' },
  'B1030': { description: 'Interior Mirror Auto-Dimming - Open Circuit', severity: 'info', system: 'Gövde Elektrik' },
  'B1031': { description: 'Interior Mirror Auto-Dimming - Short to Ground', severity: 'info', system: 'Gövde Elektrik' },
  'B1032': { description: 'Front Power Window Left - Hall Sensor', severity: 'info', system: 'Gövde Elektrik' },
  'B1033': { description: 'Front Power Window Right - Hall Sensor', severity: 'info', system: 'Gövde Elektrik' },
  'B1035': { description: 'Left Rear Window Regulator', severity: 'info', system: 'Gövde Elektrik' },
  'B1036': { description: 'Right Rear Window Regulator', severity: 'info', system: 'Gövde Elektrik' },
  'B1037': { description: 'Sliding/Roof Panel Sunroof Motor', severity: 'info', system: 'Gövde Elektrik' },
  'B1040': { description: 'Steering Column Adjustment - Hall Sensor', severity: 'info', system: 'Gövde Elektrik' },
  'B1041': { description: 'Seat Adjustment Memory - Not Learned', severity: 'info', system: 'Gövde Elektrik' },
  'B1045': { description: 'Left Mirror - Position Sensor', severity: 'info', system: 'Gövde Elektrik' },
  'B1046': { description: 'Right Mirror - Position Sensor', severity: 'info', system: 'Gövde Elektrik' },
  'B1050': { description: 'Locking Module - Left Door', severity: 'warning', system: 'Kilit' },
  'B1051': { description: 'Locking Module - Right Door', severity: 'warning', system: 'Kilit' },
  'B1055': { description: 'Tire Pressure Monitoring (TPMS) Sensor Missing', severity: 'warning', system: 'TPMS' },
  'B1056': { description: 'Tire Pressure Monitoring - System Fault', severity: 'warning', system: 'TPMS' },
  'B1060': { description: 'Wiper Motor - Park Position Not Reached', severity: 'info', system: 'Gövde Elektrik' },
  'B1061': { description: 'Wiper Motor - Faulty', severity: 'info', system: 'Gövde Elektrik' },
  'B1065': { description: 'Heated Seat Left - Open Circuit', severity: 'info', system: 'Gövde Elektrik' },
  'B1066': { description: 'Heated Seat Right - Open Circuit', severity: 'info', system: 'Gövde Elektrik' },
  'B1070': { description: 'Air Conditioning Blower Motor Circuit', severity: 'warning', system: 'İklimlendirme' },
  'B1071': { description: 'Air Conditioning Compressor Circuit', severity: 'warning', system: 'İklimlendirme' },
  'B1072': { description: 'Air Conditioning Evaporator Temperature Sensor', severity: 'info', system: 'İklimlendirme' },
  'B1075': { description: 'Seat Belt Tensioner Left - Resistance Too High', severity: 'warning', system: 'Güvenlik' },
  'B1076': { description: 'Seat Belt Tensioner Right - Resistance Too High', severity: 'warning', system: 'Güvenlik' },
  'B1080': { description: 'Horn Circuit Fault', severity: 'info', system: 'Gövde Elektrik' },
  'B1085': { description: 'Brake Light Switch (S9/1) - Signal Implausible', severity: 'critical', system: 'Fren' },
  'B1090': { description: 'Audio Gateway (A40/3) - No Communication', severity: 'warning', system: 'Multimedya' },
  'B1095': { description: 'Instrument Cluster - Display Defective', severity: 'warning', system: 'Gösterge Paneli' },
  'B1100': { description: 'SRS Airbag Warning Lamp - Driver Side', severity: 'critical', system: 'Airbag' },
  'B1101': { description: 'SRS Airbag Warning Lamp - Passenger Side', severity: 'critical', system: 'Airbag' },
  'B1102': { description: 'SRS Passenger Airbag Deactivation Fault', severity: 'critical', system: 'Airbag' },
  'B1105': { description: 'Occupant Classification System (OCS) Fault', severity: 'critical', system: 'Airbag' },
  'B1110': { description: 'Electronic Stability Program (ESP) - CAN Fault', severity: 'critical', system: 'ESP' },
  'B1115': { description: 'ABS/ESP Hydraulic Unit', severity: 'critical', system: 'ABS' },
  'B1120': { description: 'Adaptive Brake Light (S9/1) - Faulty', severity: 'warning', system: 'Fren' },
  'B1125': { description: 'Park Assist Sensor - Front Left', severity: 'info', system: 'Park Sensörü' },
  'B1126': { description: 'Park Assist Sensor - Front Right', severity: 'info', system: 'Park Sensörü' },
  'B1127': { description: 'Park Assist Sensor - Rear Left', severity: 'info', system: 'Park Sensörü' },
  'B1128': { description: 'Park Assist Sensor - Rear Right', severity: 'info', system: 'Park Sensörü' },
  'B1130': { description: 'Backup Camera - No Signal', severity: 'info', system: 'Multimedya' },
  'B1135': { description: 'Rain Sensor - Signal Outside Tolerance', severity: 'info', system: 'Gövde Elektrik' },
  'B1140': { description: 'Light Sensor - Plausibility Error', severity: 'info', system: 'Aydınlatma' },
  'B1145': { description: 'Trunk Lid Lock - Open Circuit', severity: 'info', system: 'Gövde Elektrik' },
  'B1150': { description: 'Fuel Filler Flap Solenoid - Open Circuit', severity: 'info', system: 'Gövde Elektrik' },

  // C-Series (Chassis)
  'C1000': { description: 'Steering Angle Sensor - Signal Plausibility', severity: 'warning', system: 'Direksiyon' },
  'C1001': { description: 'Steering Angle Sensor - Not Initialized', severity: 'warning', system: 'Direksiyon' },
  'C1005': { description: 'ESP/BAS Hydraulic Pump Motor', severity: 'critical', system: 'ESP' },
  'C1010': { description: 'Yaw Rate Sensor - Fault', severity: 'critical', system: 'ESP' },
  'C1011': { description: 'Yaw Rate Sensor - Signal Outside Tolerance', severity: 'warning', system: 'ESP' },
  'C1015': { description: 'Lateral Acceleration Sensor - Signal Fault', severity: 'warning', system: 'ESP' },
  'C1020': { description: 'ABS Front Left Wheel Speed Sensor', severity: 'warning', system: 'ABS' },
  'C1021': { description: 'ABS Front Right Wheel Speed Sensor', severity: 'warning', system: 'ABS' },
  'C1022': { description: 'ABS Rear Left Wheel Speed Sensor', severity: 'warning', system: 'ABS' },
  'C1023': { description: 'ABS Rear Right Wheel Speed Sensor', severity: 'warning', system: 'ABS' },
  'C1025': { description: 'ABS Sensor - Signal Plausibility (All Wheels)', severity: 'critical', system: 'ABS' },
  'C1030': { description: 'Brake Pressure Sensor - Fault', severity: 'critical', system: 'Fren' },
  'C1031': { description: 'Brake Pressure Sensor 1/2 - Signal Implausible', severity: 'critical', system: 'Fren' },
  'C1035': { description: 'Brake Pad Wear Sensor - Front Left', severity: 'warning', system: 'Fren' },
  'C1036': { description: 'Brake Pad Wear Sensor - Front Right', severity: 'warning', system: 'Fren' },
  'C1040': { description: 'Brake Fluid Level Sensor - Low', severity: 'critical', system: 'Fren' },
  'C1045': { description: 'Air Suspension - Compressor Relay', severity: 'warning', system: 'Süspansiyon' },
  'C1046': { description: 'Air Suspension - Level Sensor Fault', severity: 'warning', system: 'Süspansiyon' },
  'C1047': { description: 'Air Suspension - Compressor Run Time Exceeded', severity: 'warning', system: 'Süspansiyon' },
  'C1050': { description: 'Active Body Control (ABC) - Hydraulic Fluid Level Low', severity: 'critical', system: 'ABC' },
  'C1051': { description: 'ABC - Pressure Sensor Plausibility', severity: 'warning', system: 'ABC' },
  'C1052': { description: 'ABC - Pump Running Too Long', severity: 'warning', system: 'ABC' },
  'C1055': { description: 'ABC - Ride Height Sensor Fault', severity: 'warning', system: 'ABC' },
  'C1060': { description: 'ADAPTIVE DAMPING SYSTEM (ADS) - Valve Y1/C', severity: 'warning', system: 'Süspansiyon' },
  'C1065': { description: 'ADAPTIVE DAMPING SYSTEM (ADS) - Valve Y2/C', severity: 'warning', system: 'Süspansiyon' },
  'C1070': { description: 'AIRMATIC - Level Control Valve Y51/C', severity: 'warning', system: 'Süspansiyon' },
  'C1075': { description: 'Electronic Parking Brake - Left Actuator', severity: 'warning', system: 'Fren' },
  'C1076': { description: 'Electronic Parking Brake - Right Actuator', severity: 'warning', system: 'Fren' },
  'C1080': { description: 'Parking Brake - Voltage Supply Low', severity: 'warning', system: 'Fren' },
  'C1085': { description: 'Steering Column Lock (ESL) - Not Released', severity: 'critical', system: 'Direksiyon' },
  'C1090': { description: 'Electro-Hydraulic Steering - Motor Fault', severity: 'critical', system: 'Direksiyon' },
  'C1095': { description: '4MATIC Transfer Case - Actuator Fault', severity: 'critical', system: '4MATIC' },
  'C1100': { description: '4MATIC Transfer Case - Ratio Monitoring', severity: 'critical', system: '4MATIC' },
  'C1105': { description: 'Differential Lock - Actuator Fault', severity: 'warning', system: 'Diferansiyel' },

  // U-Series (Network/Communication)
  'U0001': { description: 'High Speed CAN Communication Bus', severity: 'critical', system: 'CAN Ağı' },
  'U0010': { description: 'Medium Speed CAN Communication Bus', severity: 'critical', system: 'CAN Ağı' },
  'U0015': { description: 'Low Speed CAN Communication Bus', severity: 'critical', system: 'CAN Ağı' },
  'U0020': { description: 'Low Speed CAN Communication Bus - Bus Off', severity: 'critical', system: 'CAN Ağı' },
  'U0025': { description: 'Low Speed CAN Communication Bus - Performance', severity: 'warning', system: 'CAN Ağı' },
  'U0028': { description: 'LIN Bus - Signal Fault', severity: 'warning', system: 'LIN Ağı' },
  'U0029': { description: 'LIN Bus - Communication Error', severity: 'warning', system: 'LIN Ağı' },
  'U0030': { description: 'Vehicle Communication Bus A', severity: 'critical', system: 'Ağ' },
  'U0035': { description: 'Vehicle Communication Bus B', severity: 'critical', system: 'Ağ' },
  'U0040': { description: 'Vehicle Communication Bus C', severity: 'critical', system: 'Ağ' },
  'U0045': { description: 'Vehicle Communication Bus D', severity: 'critical', system: 'Ağ' },
  'U0050': { description: 'Vehicle Communication Bus E', severity: 'critical', system: 'Ağ' },
  'U0055': { description: 'Vehicle Communication Bus F', severity: 'critical', system: 'Ağ' },
  'U0100': { description: 'Lost Communication with ECM/PCM A', severity: 'critical', system: 'ECU' },
  'U0101': { description: 'Lost Communication with TCM', severity: 'critical', system: 'Şanzıman' },
  'U0102': { description: 'Lost Communication with Transfer Case Control Module', severity: 'critical', system: '4MATIC' },
  'U0103': { description: 'Lost Communication with Power Steering Control Module', severity: 'critical', system: 'Direksiyon' },
  'U0104': { description: 'Lost Communication with Cruise Control Module', severity: 'warning', system: 'Hız Kontrol' },
  'U0105': { description: 'Lost Communication with Cruise Control Front Distance Range Sensor', severity: 'warning', system: 'Distronic' },
  'U0106': { description: 'Lost Communication with Glow Plug Control Module', severity: 'warning', system: 'Motor Kontrol' },
  'U0107': { description: 'Lost Communication with Throttle Actuator Control Module', severity: 'critical', system: 'Gaz Kelebeği' },
  'U0108': { description: 'Lost Communication with Alternative Fuel Control Module', severity: 'critical', system: 'Yakıt Sistemi' },
  'U0109': { description: 'Lost Communication with Fuel Pump Control Module', severity: 'critical', system: 'Yakıt Sistemi' },
  'U0110': { description: 'Lost Communication with Drive Motor Control Module A', severity: 'critical', system: 'Elektrik Motor' },
  'U0111': { description: 'Lost Communication with Hybrid/EV Battery Pack Control Module', severity: 'critical', system: 'Batarya' },
  'U0112': { description: 'Lost Communication with DC/DC Converter Control Module', severity: 'critical', system: 'Elektrik' },
  'U0113': { description: 'Lost Communication with Battery Energy Control Module A', severity: 'critical', system: 'Batarya' },
  'U0114': { description: 'Lost Communication with 4WD Control Module', severity: 'critical', system: '4MATIC' },
  'U0115': { description: 'Lost Communication with ECM/PCM B', severity: 'critical', system: 'ECU' },
  'U0116': { description: 'Lost Communication with NOx Sensor Control Module', severity: 'warning', system: 'Emisyon' },
  'U0117': { description: 'Lost Communication with Selective Catalytic Reduction (SCR) System', severity: 'warning', system: 'Emisyon' },
  'U0118': { description: 'Lost Communication with Transmission Range Sensor Module', severity: 'critical', system: 'Şanzıman' },
  'U0119': { description: 'Lost Communication with Battery Pack Control Module B', severity: 'critical', system: 'Batarya' },
  'U0120': { description: 'Lost Communication with Exhaust Gas Recirculation Control Module', severity: 'warning', system: 'Emisyon' },
  'U0121': { description: 'Lost Communication with ABS Control Module', severity: 'critical', system: 'ABS' },
  'U0122': { description: 'Lost Communication with Vehicle Dynamics Control Module', severity: 'critical', system: 'ESP' },
  'U0123': { description: 'Lost Communication with Yaw Rate Sensor Module', severity: 'critical', system: 'ESP' },
  'U0124': { description: 'Lost Communication with Steering Angle Sensor Module', severity: 'critical', system: 'Direksiyon' },
  'U0125': { description: 'Lost Communication with Multi-Axle Acceleration Sensor Module', severity: 'critical', system: 'ESP' },
  'U0126': { description: 'Lost Communication with Steering Column Control Module', severity: 'critical', system: 'Direksiyon' },
  'U0127': { description: 'Lost Communication with Tire Pressure Monitor Module', severity: 'warning', system: 'TPMS' },
  'U0128': { description: 'Lost Communication with Parking Assist Control Module', severity: 'warning', system: 'Park Sensörü' },
  'U0129': { description: 'Lost Communication with Brake System Control Module', severity: 'critical', system: 'Fren' },
  'U0130': { description: 'Lost Communication with Steering Effort Control Module', severity: 'critical', system: 'Direksiyon' },
  'U0131': { description: 'Lost Communication with Power Steering Control Module B', severity: 'critical', system: 'Direksiyon' },
  'U0140': { description: 'Lost Communication with Body Control Module', severity: 'critical', system: 'Gövde Elektrik' },
  'U0141': { description: 'Lost Communication with Left Front Door Control Module', severity: 'warning', system: 'Kapı Kontrol' },
  'U0142': { description: 'Lost Communication with Right Front Door Control Module', severity: 'warning', system: 'Kapı Kontrol' },
  'U0143': { description: 'Lost Communication with Left Rear Door Control Module', severity: 'warning', system: 'Kapı Kontrol' },
  'U0144': { description: 'Lost Communication with Right Rear Door Control Module', severity: 'warning', system: 'Kapı Kontrol' },
  'U0145': { description: 'Lost Communication with Gateway A', severity: 'critical', system: 'Ağ' },
  'U0146': { description: 'Lost Communication with Gateway B', severity: 'critical', system: 'Ağ' },
  'U0147': { description: 'Lost Communication with Seat Control Module A', severity: 'warning', system: 'Koltuk' },
  'U0148': { description: 'Lost Communication with Seat Control Module B', severity: 'warning', system: 'Koltuk' },
  'U0149': { description: 'Lost Communication with Air Conditioning Control Module', severity: 'warning', system: 'İklimlendirme' },
  'U0150': { description: 'Lost Communication with Instrument Panel Control Module', severity: 'critical', system: 'Gösterge Paneli' },
  'U0151': { description: 'Lost Communication with SCM (Steering Column Control Module)', severity: 'critical', system: 'Direksiyon' },
  'U0155': { description: 'Lost Communication with Instrument Panel Cluster (IPC) Control Module', severity: 'critical', system: 'Gösterge Paneli' },
  'U0156': { description: 'Lost Communication with HVAC Control Module', severity: 'warning', system: 'İklimlendirme' },
  'U0160': { description: 'Lost Communication with Audio System Control Module', severity: 'warning', system: 'Multimedya' },
  'U0164': { description: 'Lost Communication with HVAC Control Module B', severity: 'warning', system: 'İklimlendirme' },
  'U0168': { description: 'Lost Communication with Vehicle Immobilizer Control Module', severity: 'critical', system: 'Immobilizer' },
  'U0170': { description: 'Lost Communication with Image Processing Module A', severity: 'warning', system: 'Multimedya' },
  'U0171': { description: 'Lost Communication with Image Processing Module B', severity: 'warning', system: 'Multimedya' },
  'U0180': { description: 'Lost Communication with Aerial (Antenna) Control Module', severity: 'warning', system: 'Multimedya' },
  'U0184': { description: 'Lost Communication with Radio', severity: 'info', system: 'Multimedya' },
  'U0186': { description: 'Lost Communication with Audio Amplifier', severity: 'info', system: 'Multimedya' },
  'U0190': { description: 'Lost Communication with Digital Audio Broadcast (DAB) Module', severity: 'info', system: 'Multimedya' },
  'U0199': { description: 'Lost Communication with Body Control Module B', severity: 'critical', system: 'Gövde Elektrik' },
  'U0200': { description: 'Lost Communication with Door Control Module', severity: 'warning', system: 'Kapı Kontrol' },
  'U0201': { description: 'Lost Communication with Mirror Control Module', severity: 'warning', system: 'Gövde Elektrik' },
  'U0202': { description: 'Lost Communication with Seat Memory Control Module', severity: 'warning', system: 'Koltuk' },
  'U0203': { description: 'Lost Communication with Sunroof Control Module', severity: 'warning', system: 'Gövde Elektrik' },
  'U0204': { description: 'Lost Communication with Window Control Module', severity: 'warning', system: 'Gövde Elektrik' },
  'U0205': { description: 'Lost Communication with Wiper Control Module', severity: 'warning', system: 'Gövde Elektrik' },
  'U0210': { description: 'Lost Communication with Headlamp Leveling Control Module', severity: 'warning', system: 'Aydınlatma' },
  'U0212': { description: 'Lost Communication with Exterior Light Control Module', severity: 'warning', system: 'Aydınlatma' },
  'U0215': { description: 'Lost Communication with Occupant Classification System Module', severity: 'critical', system: 'Airbag' },
  'U0220': { description: 'Lost Communication with Rear Gate Module', severity: 'warning', system: 'Gövde Elektrik' },
  'U0225': { description: 'Lost Communication with Sunroof Motor Control Module', severity: 'warning', system: 'Gövde Elektrik' },
  'U0226': { description: 'Lost Communication with Mirror Control Module B', severity: 'warning', system: 'Gövde Elektrik' },
  'U0230': { description: 'Lost Communication with Reverse Warning Control Module', severity: 'warning', system: 'Park Sensörü' },
  'U0235': { description: 'Lost Communication with Cruise Control Module B', severity: 'warning', system: 'Hız Kontrol' },
  'U0240': { description: 'Lost Communication with Headlamp Control Module', severity: 'warning', system: 'Aydınlatma' },
  'U0250': { description: 'Lost Communication with Cruise Control Distance Sensor', severity: 'warning', system: 'Distronic' },
  'U0255': { description: 'Lost Communication with Blind Spot Detection Module', severity: 'warning', system: 'Kör Nokta' },
  'U0260': { description: 'Lost Communication with Lane Departure Warning Module', severity: 'warning', system: 'Şerit Takip' },
  'U0265': { description: 'Lost Communication with Night Vision Module', severity: 'warning', system: 'Gece Görüşü' },
  'U0270': { description: 'Lost Communication with Head-up Display Module', severity: 'warning', system: 'HUD' },
  'U0300': { description: 'Internal Control Module Software Incompatibility', severity: 'critical', system: 'ECU' },
  'U0301': { description: 'Internal Control Module Software Incompatibility with TCM', severity: 'critical', system: 'Şanzıman' },
  'U0302': { description: 'Internal Control Module Software Incompatibility with Transfer Case Module', severity: 'critical', system: '4MATIC' },
  'U0305': { description: 'Internal Control Module Software Incompatibility with Traction Control Module', severity: 'critical', system: 'ESP' },
  'U0306': { description: 'Internal Control Module Software Incompatibility with Glow Plug Module', severity: 'warning', system: 'Motor Kontrol' },
  'U0307': { description: 'Internal Control Module Software Incompatibility with Throttle Actuator', severity: 'critical', system: 'Gaz Kelebeği' },
  'U0310': { description: 'Internal Control Module Software Incompatibility with 4WD Module', severity: 'critical', system: '4MATIC' },
  'U0314': { description: 'Internal Control Module Software Incompatibility with ABS Module', severity: 'critical', system: 'ABS' },
  'U0315': { description: 'Internal Control Module Software Incompatibility with ESP Module', severity: 'critical', system: 'ESP' },
  'U0316': { description: 'Internal Control Module Software Incompatibility with SRS Module', severity: 'critical', system: 'Airbag' },
  'U0320': { description: 'Internal Control Module Software Incompatibility with PCM', severity: 'critical', system: 'ECU' },
  'U0324': { description: 'Internal Control Module Software Incompatibility with HVAC Module', severity: 'warning', system: 'İklimlendirme' },
  'U0326': { description: 'Internal Control Module Software Incompatibility with Seat Control', severity: 'warning', system: 'Koltuk' },
  'U0400': { description: 'Invalid Data Received from ECM/PCM A', severity: 'critical', system: 'ECU' },
  'U0401': { description: 'Invalid Data Received from TCM', severity: 'critical', system: 'Şanzıman' },
  'U0402': { description: 'Invalid Data Received from Transfer Case Module', severity: 'critical', system: '4MATIC' },
  'U0405': { description: 'Invalid Data Received from Cruise Control Module', severity: 'warning', system: 'Hız Kontrol' },
  'U0410': { description: 'Invalid Data Received from 4WD Module', severity: 'critical', system: '4MATIC' },
  'U0414': { description: 'Invalid Data Received from ABS Module', severity: 'critical', system: 'ABS' },
  'U0415': { description: 'Invalid Data Received from ESP Module', severity: 'critical', system: 'ESP' },
  'U0416': { description: 'Invalid Data Received from Steering Angle Sensor', severity: 'critical', system: 'Direksiyon' },
  'U0420': { description: 'Invalid Data Received from Body Control Module', severity: 'critical', system: 'Gövde Elektrik' },
  'U0421': { description: 'Invalid Data Received from Door Control Module', severity: 'warning', system: 'Kapı Kontrol' },
  'U0425': { description: 'Invalid Data Received from SRS Module', severity: 'critical', system: 'Airbag' },
  'U0430': { description: 'Invalid Data Received from PCM', severity: 'critical', system: 'ECU' },
  'U0440': { description: 'Invalid Data Received from Immobilizer Module', severity: 'critical', system: 'Immobilizer' },
  'U0450': { description: 'Invalid Data Received from Lane Departure Module', severity: 'warning', system: 'Şerit Takip' },
  'U0460': { description: 'Invalid Data Received from Parking Assist Module', severity: 'warning', system: 'Park Sensörü' },
  'U0500': { description: 'Invalid Data Received from Unknown Module', severity: 'warning', system: 'Ağ' },
  'U0501': { description: 'Invalid Data Received from Door Control Module B', severity: 'warning', system: 'Kapı Kontrol' },
  'U1000': { description: 'CAN Bus Communication Error', severity: 'critical', system: 'CAN Ağı' },
  'U1001': { description: 'SAM Communication Error - CAN Bus', severity: 'critical', system: 'CAN Ağı' },
  'U1002': { description: 'ME-SFI CAN Bus Communication Error', severity: 'critical', system: 'CAN Ağı' },
  'U1003': { description: 'ESP CAN Bus Communication Error', severity: 'critical', system: 'CAN Ağı' },
  'U1004': { description: 'Electronic Ignition Lock (EIS) CAN Bus Error', severity: 'critical', system: 'Immobilizer' },
  'U1005': { description: 'Automatic Transmission CAN Bus Error', severity: 'critical', system: 'Şanzıman' },
  'U1100': { description: 'Signal CAN-B Off - Front SAM', severity: 'critical', system: 'SAM Modülü' },
  'U1101': { description: 'Signal CAN-B Off - Rear SAM', severity: 'critical', system: 'SAM Modülü' },
  'U1102': { description: 'Signal CAN-B Off - ECU', severity: 'critical', system: 'ECU' },
  'U1103': { description: 'Signal CAN-B Off - ESP', severity: 'critical', system: 'ESP' },
  'U1105': { description: 'Signal CAN-B Off - Instrument Cluster', severity: 'critical', system: 'Gösterge Paneli' },
  'U1106': { description: 'Signal CAN-B Off - EIS', severity: 'critical', system: 'Immobilizer' },
  'U1110': { description: 'Signal CAN-B Off - Airbag', severity: 'critical', system: 'Airbag' },
  'U1115': { description: 'Signal CAN-B Off - Automatic Transmission', severity: 'critical', system: 'Şanzıman' },
  'U1120': { description: 'Signal CAN-B Off - Audio Gateway', severity: 'warning', system: 'Multimedya' },
  'U1200': { description: 'Multiplexed CAN Signal - Missing/Implausible', severity: 'warning', system: 'Ağ' },
  'U1201': { description: 'Multiplexed CAN Signal - Out of Range', severity: 'warning', system: 'Ağ' },
  'U1202': { description: 'Multiplexed CAN Signal - Error', severity: 'warning', system: 'Ağ' },
}

export async function GET(req: NextRequest, { params }: { params: Promise<{ id: string }> }) {
  try {
    const { id } = await params

    // Get saved fault codes for the session
    const faultCodes = await db.faultCode.findMany({
      where: { sessionId: id },
      orderBy: { createdAt: 'desc' }
    })

    return NextResponse.json({
      faultCodes,
      mbDatabase: MB_FAULT_CODES
    })
  } catch (error: any) {
    return NextResponse.json({ error: error.message }, { status: 500 })
  }
}

export async function POST(req: NextRequest, { params }: { params: Promise<{ id: string }> }) {
  try {
    const { id } = await params
    const body = await req.json()
    const { codes } = body // Accept array of codes

    if (!codes || !Array.isArray(codes) || codes.length === 0) {
      // Fallback to single code
      const { code, description, severity, status } = body
      if (!code) {
        return NextResponse.json({ error: 'Kod zorunlu' }, { status: 400 })
      }

      // Look up in MB database
      const mbInfo = MB_FAULT_CODES[code.toUpperCase()]
      const faultCode = await db.faultCode.create({
        data: {
          sessionId: id,
          code: code.toUpperCase(),
          description: description || mbInfo?.description || null,
          severity: severity || mbInfo?.severity || 'warning',
          status: status || 'active'
        }
      })

      return NextResponse.json({ faultCode, mbInfo }, { status: 201 })
    }

    // Batch create fault codes
    const createdCodes = []
    for (const item of codes) {
      const codeStr = typeof item === 'string' ? item : item.code
      const desc = typeof item === 'string' ? null : item.description
      const sev = typeof item === 'string' ? null : item.severity

      const mbInfo = MB_FAULT_CODES[codeStr.toUpperCase()]

      const faultCode = await db.faultCode.create({
        data: {
          sessionId: id,
          code: codeStr.toUpperCase(),
          description: desc || mbInfo?.description || null,
          severity: sev || mbInfo?.severity || 'warning',
          status: 'active'
        }
      })
      createdCodes.push({ faultCode, mbInfo })
    }

    return NextResponse.json({ faultCodes: createdCodes }, { status: 201 })
  } catch (error: any) {
    return NextResponse.json({ error: error.message }, { status: 500 })
  }
}
